//import com.mysql.cj.jdbc.Driver;
//
//import java.sql.*;
//
//public class jdbcLec {
////    Instantiate Driver to register the built in java driver manager
//
//    public static void main(String[] args) throws SQLException {
//
//
//        Config config = new Config();
//        Connection connection = DriverManager.getConnection(
//                config.getUrl(),
//                config.getUser(),
//                config.getPassword()
//        );
//
//
//
//        DriverManager.registerDriver(new Driver() {});
//
//
//        Statement statement = connection.createStatement();
//
//
//
//
////        Handling Result Sets
//
//        String selectQuery = "SELECT * FROM albums";
//
//        ResultSet rs = statement.executeQuery(selectQuery);
//        // 'rs' is an instance of ResultSet
//        while (rs.next()) {
//            // do something with each row
//            System.out.println("Here's an album:");
//            System.out.println("  id: " + rs.getLong("id"));
//            System.out.println("  artist: " + rs.getString("artist"));
//            System.out.println("  name: " + rs.getString("name"));
//        }

////        Insert Query
//        String query = "INSERT INTO albums (artist, name, release_date, genre, sales) VALUES('Nelly Furtado', 'Loose', 2006, 'Pop, Urban, R&B', 12.5)";
//
//
//
////        This gives us access to id's that are automatically generated by the database
//        statement.executeUpdate(query, Statement.RETURN_GENERATED_KEYS);
//
////        Set generated keys to a result set to iterate through
//        ResultSet rsKeys = statement.getGeneratedKeys();
//        if (rsKeys.next()) {
//            System.out.println("Inserted a new record! New id: " + rsKeys.getLong(1));
//        }

//    }
//
//}
